# Generated by Django 2.2.7 on 2019-11-14 11:43

import auto.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('RU', 'Русский'), ('EN', 'English')], default='RU', max_length=2, verbose_name='Lang')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1950), auto.models.max_value_current_year])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ManyToManyField(to='auto.CarNameModel')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
